image: joaodubas/nodejs
env:
    - LVLDB_HOST=localhost
    - LVLDB_PORT=3001
script:
    - npm install
    - npm test
services:
#    - joaodubas/multilevel
notify:
    email:
        recipients:
            - ling@erealm.com.my
